# docker-compose.yml
version: '3'
services:

    nginx:
        container_name: nginx
        build: ./nginx
        image: docker_compose/nginx
        restart: always
        ports:
          - "80:80"
        volumes:
          - ./djecommerce:/srv/docker-server
          - ./log:/var/log/nginx
        depends_on:
          - django

    django:
        container_name: django
        build: ./djecommerce
        image: docker_compose/django
        restart: always
        environment :
                PYTHONPATH: /home/ubuntu/docker-server/djecommerce
        command: uwsgi --ini uwsgi.ini
        volumes:
          - ./djecommerce:/srv/docker-server
          - ./log:/var/log/uwsgi
